name: PHP static analysis with lowest dependencies

on:
  push:
    branches:
      - master
  pull_request: null

jobs:
  phpstan:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [ '7.4', '8.0', '8.1' ]

    name: PHPStan with lowest dependencies - PHP ${{ matrix.php }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none # disable xdebug, pcov

      - name: Composer update
        run: composer update --prefer-lowest --no-progress --no-interaction

      - name: Install PHPStan as dev dependency
        run: composer require phpstan/phpstan --dev

      - name: PHPStan analyse
        run: vendor/bin/phpstan analyze src --level=8 --no-progress
